/**
 * 构建脚本：创建 react-devtools-core stub 并构建 exe
 */
import { mkdirSync, readFileSync, writeFileSync } from 'fs';
import { createHash } from 'crypto';

// 创建 stub 替代 15MB 的 react-devtools-core
const stubDir = 'node_modules/react-devtools-core';
mkdirSync(stubDir, { recursive: true });
writeFileSync(`${stubDir}/index.js`, 'export function connectToDevTools() {}\nexport default { connectToDevTools };\n');
writeFileSync(`${stubDir}/package.json`, JSON.stringify({ type: 'module', main: 'index.js' }));
console.log('Created react-devtools-core stub');

// 将轻量 Agent runner 嵌入到 standalone exe 中，发布后无需依赖 npm 包源码。
const agentLiteSource = readFileSync('bin/agent-lite.js', 'utf-8');
const sourceHash = createHash('sha256').update(agentLiteSource).digest('hex');
mkdirSync('src/agent', { recursive: true });
writeFileSync(
  'src/agent/embedded-agent-lite-source.ts',
  `// Auto-generated by scripts/prebuild.ts. Do not edit manually.\n// Hash: ${sourceHash}\nexport const AGENT_LITE_SOURCE = ${JSON.stringify(agentLiteSource)};\nexport const AGENT_LITE_HASH = "${sourceHash}";\n`,
  'utf-8',
);
console.log(`Embedded agent-lite runner source (hash: ${sourceHash.slice(0, 16)}...)`);
